### ISSUE TITLE
bugs in Gap2Seq

### ISSUE THREAD

**Issue by Jordi-V** [rikuu/Gap2Seq#10]
Hi every one,

I installed the program Gap2Seq, and I found different bugs (or I hope) in the binary Gap2Seq.

when you ran the Gap2Seq like this:
Gap2Seq --vcf insertions_filtered.vcf -t 48 --reference genome.fa --filled genome.fill.fa --reads insilico3_1.fq.gz,insilico3_2.fq.gz

I ran the Gap2Seq to genotype a vcf which contain insertions already detected by Pamir. You could found the following error:

 line 329 "f" is not a variable (or something like that)...
If you go to this line you will find the f variable, which I consider the correct variable is reference_file, the same happens in line 340.

Even more in line 339, you should change the "r+" by "w+", because you need create some files... If you do this changes and install the HDF5 version 1.8.18 the program will works.

My only question is know how I will get the output, the program overwrite the vcf? or generate a new one?
I hope this helps

Jordi

**Comment by Jordi-V** [comment]
Dear, 

I only want to upload that gap2seq have several bugs... Now after run the genotyping option with vcf (where I dont know how you give the genotype, in vcf?? or how??) appear a new bug where I've no idea how solve.

this is the command:
/gpfs/projects/bsc05/jordivalls/apps/GAP2SEQ/Gap2Seq/build/Gap2Seq --vcf /gpfs/projects/bsc05/jordivalls/GCAT/Pamir/insilico_3/insertions_filtered.vcf -t 1 --reference /gpfs/projects/bsc05/jordivalls/GCAT/human_ref_PANCANCER/genome.fa --filled /gpfs/projects/bsc05/jordivalls/GCAT/Pamir/gap2seq/genome.fill.fa --reads /gpfs/projects/bsc05/jordivalls/new_insilico/insilico_3/fastq_bam/insilico_tumor/BAM/bam_mem/bam_merge_all/bam_recalibrator/fastq/insilico3_1.fq.gz,/gpfs/projects/bsc05/jordivalls/new_insilico/insilico_3/fastq_bam/insilico_tumor/BAM/bam_mem/bam_merge_all/bam_recalibrator/fastq/insilico3_2.fq.gz

and this is the new bug:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Traceback (most recent call last):
  File "/gpfs/projects/bsc05/jordivalls/apps/GAP2SEQ/Gap2Seq/build/Gap2Seq", line 500, in <module>
    args['best_only'], args['reads'], args['threads'])
  File "/gpfs/projects/bsc05/jordivalls/apps/GAP2SEQ/Gap2Seq/build/Gap2Seq", line 243, in fill_scaffolds
    subprocess.check_call(command)
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/gpfs/projects/bsc05/jordivalls/apps/GAP2SEQ/Gap2Seq/build/Gap2Seq-core', '-k', '31', '-fuz', '10', '-solid', '2', '-nb-cores', '1', '-dist-error', '500', '-max-mem', '20', '-randseed', '0', '-reads', '/gpfs/projects/bsc05/jordivalls/new_insilico/insilico_3/fastq_bam/insilico_tumor/BAM/bam_mem/bam_merge_all/bam_recalibrator/fastq/insilico3_1.fq.gz,/gpfs/projects/bsc05/jordivalls/new_insilico/insilico_3/fastq_bam/insilico_tumor/BAM/bam_mem/bam_merge_all/bam_recalibrator/fastq/insilico3_2.fq.gz', '-filled', '/gpfs/projects/bsc05/jordivalls/GCAT/Pamir/gap2seq/genome.fill.fa', '-scaffolds', 'tmp.bed']' died with <Signals.SIGABRT: 6>

cannot allocate the memory.... I dont know where is the bug. Even more when I run the program with filter version, appear a new bug, because cannot create a tmp.filled, which I solve it creating the file manually.... because I dont know where create this file in the binary.

I dont know If anyone will reply me, I will appreciate how to solve these mistakes and know how you give the genotyping information about de novo insertions... because when I ran the program in filtered version, the output is full but I dont see any genotype....

Thanks for your time

Jordi

**Comment by vrohnie** [comment]
Hey,
This is just a guess, but did you try to set the --max-mem option to something higher than 20GB ?

Best regards,
Veronika

**Comment by Jordi-V** [comment]
Thanks for your reply but I've 96 GB of memory, I dont think that this is the problem....
